project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.ipynb"

website:
  # title: ""
  # favicon: favicon/favicon.png
  search: true
  page-navigation: true
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: "Software Library"
        menu:
          - href: "https://hemdag.readthedocs.io/en/latest/"
            text: 'HEMDAG'
          - href: "https://obogaf-parser.readthedocs.io/en/latest/"
            text: "obogaf-parser"
          - href: "https://github.com/uzh/ezRun/commits?author=marconotaro"
            text: "Contribution to ezRun"
          - href: "https://github.com/uzh/sushi/commits?author=marconotaro"
            text: "Contribution to SUSHI"
      - text: "Machine Learning"
        menu:
          - href: "biomarker-discovery-ornish.ipynb"
            text: "Identifying biomarkers associated with weight loss using a Bayesian-optimized classifier"
          - href: "predict-housing-prices.ipynb"
            text: "Predicting housing prices in California"
          - href: "r4_predict_erstatus.ipynb"
            text: "Predicting biomarker status imputing missing values"
          - href: "cnn_vs_fnn.ipynb"
            text: "Predicting protein localizations with pythorch"
          - href: "ml-graph.ipynb"
            text: "Predicting salary and new connections with scikit-learn"
          - href: "ml-video.ipynb"
            text: "Predicting viewer engagement with scikit-learn"
      - text: "Genomics"
        menu:
          - href: "cancer-subtypes.qmd"
            text: "Identification of breast cancer subtypes"
      - text: "AI tools"
        menu:
          - href: "https://github.com/marconotaro/llm-sib"
            text: "A RAG framework for bioinformatics applications"
      - text: "Data Viz"
        menu:
          - href: swissalps_map.ipynb
          - href: "weather-records.ipynb"
          - href: "detroit-wiki.ipynb"
    tools:
      - icon: github
        href: https://github.com/marconotaro/portfolio
      - icon: globe-americas
        href: https://marconotaro.github.io
  page-footer:
    left: "&copy; Copyright 2025, Marco Notaro"
    right: "[MIT License](license.md)"

format:
  html:
    respect-user-color-scheme: true
    theme:
      dark: darkly
      light: flatly
    toc: true
    toc-location: left
    toc-depth: 4
    code-link: true
    code-fold: false
    code-tools: true
    embed-resources: false
    include-in-header:
      - text: |
          <link href="favicon/favicon.png" rel="icon">
          <link href="favicon/apple-touch-icon.png" rel="apple-touch-icon">

execute:
  freeze: auto
  cache: true
  tidy: true
  echo: true
  message: false
  warning: false
  fig-align: center
  fig-width: 10
  fig-height: 8
  fig-dpi: 300
  dev: png