name: ml-classic
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - affine=2.4.0
  - alsa-lib=1.2.15.3
  - asttokens=3.0.1
  - attrs=25.4.0
  - backports.zstd=1.3.0
  - blosc=1.21.6
  - branca=0.8.2
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - cairo=1.18.4
  - certifi=2026.1.4
  - charset-normalizer=3.4.4
  - click=8.3.1
  - click-plugins=1.1.1.2
  - cligj=0.7.2
  - comm=0.2.3
  - contextily=1.7.0
  - contourpy=1.3.3
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dbus=1.16.2
  - debugpy=1.8.20
  - decorator=5.2.1
  - double-conversion=3.4.0
  - executing=2.2.1
  - folium=0.20.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.1
  - freetype=2.14.1
  - freexl=2.0.0
  - geographiclib=2.1
  - geopy=2.4.1
  - geos=3.14.1
  - giflib=5.2.2
  - graphite2=1.3.14
  - h2=4.3.0
  - harfbuzz=12.3.2
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=78.2
  - idna=3.11
  - ipykernel=7.2.0
  - ipython=9.10.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.3
  - json-c=0.18
  - jupyter_client=8.8.0
  - jupyter_core=5.9.1
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.18
  - ld_impl_linux-64=2.45.1
  - lerc=4.0.0
  - libarchive=3.8.5
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libclang-cpp21.1=21.1.8
  - libclang13=21.1.8
  - libcups=2.3.3
  - libcurl=8.18.0
  - libdeflate=1.25
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgdal-core=3.12.2
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.86.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libhwy=1.3.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - libjxl=0.11.2
  - libkml=1.3.0
  - liblapack=3.11.0
  - libllvm21=21.1.8
  - liblzma=5.8.2
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libpciaccess=0.18
  - libpng=1.6.55
  - libpq=18.1
  - librttopo=1.1.0
  - libsodium=1.0.20
  - libspatialite=5.1.0
  - libsqlite=3.51.2
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libuuid=2.41.3
  - libvulkan-loader=1.4.341.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.13.1
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxml2-devel=2.15.1
  - libxslt=1.1.43
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - lzo=2.10
  - markupsafe=3.0.3
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - mercantile=1.2.1
  - minizip=4.0.10
  - munkres=1.1.4
  - muparser=2.3.5
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.6.1
  - numpy=2.4.2
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openssl=3.6.1
  - packaging=26.0
  - pandas=3.0.0
  - parso=0.8.6
  - patsy=1.0.2
  - pcre2=10.47
  - pexpect=4.9.0
  - pillow=12.1.1
  - pip=26.0.1
  - pixman=0.46.4
  - platformdirs=4.5.1
  - proj=9.7.1
  - prompt-toolkit=3.0.52
  - psutil=7.2.2
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - pyparsing=3.3.2
  - pyside6=6.10.2
  - pysocks=1.7.1
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python_abi=3.11
  - pyzmq=27.1.0
  - qhull=2020.2
  - qt6-main=6.10.2
  - rasterio=1.4.4
  - readline=8.3
  - requests=2.32.5
  - scikit-learn=1.8.0
  - scipy=1.17.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=82.0.0
  - six=1.17.0
  - snappy=1.2.2
  - snuggs=1.4.7
  - sqlite=3.51.2
  - stack_data=0.6.3
  - statsmodels=0.14.6
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tornado=6.5.4
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - tzdata=2025c
  - unicodedata2=17.0.0
  - uriparser=0.9.8
  - urllib3=2.6.3
  - wayland=1.24.0
  - wcwidth=0.6.0
  - wheel=0.46.3
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.6
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xerces-c=3.3.0
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.13
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.7
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.7
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.5
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.7
  - xyzservices=2025.11.0
  - zeromq=4.3.5
  - zlib=1.3.1
  - zlib-ng=2.3.3
  - zstd=1.5.7
